-- ==========================================
-- 0. PREPARAR EL ENTORNO (LA CLAVE ESTÁ AQUÍ)
-- ==========================================
CREATE SCHEMA IF NOT EXISTS public;
SET search_path TO public;

-- ==========================================
-- 1. CREACIÓN DE TABLAS Y SECUENCIAS
-- ==========================================

CREATE TABLE empresas (
    id bigint NOT NULL,
    cif character varying(255) NOT NULL,
    direccion_calle character varying(255),
    direccion_ciudad character varying(255),
    direccion_cp character varying(255),
    direccion_numero character varying(255),
    direccion_pais character varying(255),
    direccion_provincia character varying(255),
    email character varying(150),
    iban character varying(34),
    nombre character varying(255) NOT NULL,
    precio_dieta_defecto numeric(10,2),
    precio_hora_espera_defecto numeric(10,2),
    precio_km_defecto numeric(10,2),
    telefono character varying(255) NOT NULL,
    usuario_id bigint NOT NULL
);

ALTER TABLE empresas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME empresas_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE facturas (
    id bigint NOT NULL,
    cuenta_bancaria character varying(255),
    estado character varying(20),
    fecha_emision date NOT NULL,
    forma_pago character varying(255),
    importe_irpf numeric(10,2),
    importe_iva numeric(10,2),
    numero_factura character varying(255) NOT NULL,
    observaciones text,
    porcentaje_irpf numeric(5,2),
    porcentaje_iva numeric(5,2) NOT NULL,
    total_bruto numeric(100,2) NOT NULL,
    total_factura numeric(100,2) NOT NULL,
    empresa_id bigint NOT NULL,
    usuario_id bigint NOT NULL
);

ALTER TABLE facturas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME facturas_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE login_attempts (
    id bigint NOT NULL,
    clave character varying(255) NOT NULL,
    intentos integer NOT NULL,
    ultima_modificacion timestamp(6) without time zone NOT NULL
);

ALTER TABLE login_attempts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME login_attempts_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE servicios (
    id bigint NOT NULL,
    albaran character varying(255),
    cliente_final character varying(255),
    conductor character varying(255),
    destino character varying(255),
    dieta boolean,
    fecha_servicio date NOT NULL,
    horas_espera numeric(100,2),
    importe_espera numeric(100,2),
    importe_servicio numeric(100,2) NOT NULL,
    km integer NOT NULL,
    matricula_vehiculo character varying(255),
    observaciones text,
    orden integer,
    origen character varying(255),
    precio_dieta numeric(100,2),
    precio_km numeric(100,2) NOT NULL,
    tipo_servicio character varying(255) NOT NULL,
    empresa_id bigint NOT NULL,
    factura_id bigint
);

ALTER TABLE servicios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME servicios_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE tokens_revocados (
    id bigint NOT NULL,
    fecha_expiracion timestamp(6) without time zone NOT NULL,
    token character varying(512) NOT NULL
);

ALTER TABLE tokens_revocados ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME tokens_revocados_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE usuario_roles (
    usuario_id bigint NOT NULL,
    rol character varying(255)
);

CREATE TABLE usuarios (
    id bigint NOT NULL,
    cuenta_bancaria character varying(24),
    direccion_calle character varying(255),
    direccion_ciudad character varying(255),
    direccion_cp character varying(255),
    direccion_numero character varying(255),
    direccion_pais character varying(255),
    direccion_provincia character varying(255),
    email character varying(255) NOT NULL,
    imagen_url character varying(255),
    nif character varying(9),
    nombre character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    telefono character varying(9)
);

ALTER TABLE usuarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME usuarios_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

-- ==========================================
-- 2. CLAVES PRIMARIAS Y RESTRICCIONES (UNIQUE)
-- ==========================================

ALTER TABLE ONLY empresas ADD CONSTRAINT empresas_pkey PRIMARY KEY (id);
ALTER TABLE ONLY facturas ADD CONSTRAINT facturas_pkey PRIMARY KEY (id);
ALTER TABLE ONLY login_attempts ADD CONSTRAINT login_attempts_pkey PRIMARY KEY (id);
ALTER TABLE ONLY servicios ADD CONSTRAINT servicios_pkey PRIMARY KEY (id);
ALTER TABLE ONLY tokens_revocados ADD CONSTRAINT tokens_revocados_pkey PRIMARY KEY (id);
ALTER TABLE ONLY usuarios ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);

ALTER TABLE ONLY login_attempts ADD CONSTRAINT ukfy1bq9vrdh327ek4hpgj8jh6i UNIQUE (clave);
ALTER TABLE ONLY facturas ADD CONSTRAINT ukm3ybkrgx2m3tj1tk6rp7sqjxt UNIQUE (numero_factura);
ALTER TABLE ONLY tokens_revocados ADD CONSTRAINT uksvutquepwyiy8h1lyb0cacxa9 UNIQUE (token);

-- ==========================================
-- 3. RELACIONES (CLAVES FORÁNEAS)
-- ==========================================

ALTER TABLE ONLY empresas ADD CONSTRAINT fk18r3jxa6l8a3wi8dngya6kx9t FOREIGN KEY (usuario_id) REFERENCES usuarios(id);
ALTER TABLE ONLY facturas ADD CONSTRAINT fk7h3qmligsy2a1mp3ei41rdqag FOREIGN KEY (usuario_id) REFERENCES usuarios(id);
ALTER TABLE ONLY servicios ADD CONSTRAINT fkd05y97js7fi4dnemp51g3pg3q FOREIGN KEY (empresa_id) REFERENCES empresas(id);
ALTER TABLE ONLY facturas ADD CONSTRAINT fkd3979hd5khrjhli95gylcf3ag FOREIGN KEY (empresa_id) REFERENCES empresas(id);
ALTER TABLE ONLY servicios ADD CONSTRAINT fkeawxkyjgf7lapia9wvq4jpkn5 FOREIGN KEY (factura_id) REFERENCES facturas(id);
ALTER TABLE ONLY usuario_roles ADD CONSTRAINT fkuu9tea04xb29m2km5lwe46ua FOREIGN KEY (usuario_id) REFERENCES usuarios(id);

